name: "Tauri Build"

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libglib2.0-dev \
            build-essential \
            curl \
            wget \
            pkg-config \
            libssl-dev \
            librsvg2-dev \
            libwebkit2gtk-4.0-dev


      - name: Install frontend dependencies (includes Tauri CLI)
        working-directory: ./desktop
        shell: bash
        run: |
          rm -rf node_modules package-lock.json bun.lockb
          bun install

      - name: Build with Tauri
        working-directory: ./desktop
        run: bun run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-tauri-binaries
          path: desktop/src-tauri/target/release/bundle/
